ign_sim_pointcloud_tool:
  ros__parameters:
    pcd_topic: livox/lidar
    n_scan: 32
    horizon_scan: 1875
    ang_bottom: 7.0
    ang_res_y: 1.84375  # (7+52) / 32

point_lio:
  ros__parameters:
    use_imu_as_input: False
    prop_at_freq_of_imu: True
    check_satu: True
    init_map_size: 10
    point_filter_num: 8
    space_down_sample: True
    filter_size_surf: 0.2
    filter_size_map: 0.2
    ivox_nearby_type: 18
    runtime_pos_log_enable: False

    common:
      lid_topic: "livox/lidar"
      imu_topic: "livox/imu"
      con_frame: False
      con_frame_num: 1
      cut_frame: False
      cut_frame_time_interval: 0.05
      time_diff_lidar_to_imu: 0.0

    prior_pcd:
      enable: False

    preprocess:
      lidar_type: 1                                     # 1 for Livox serials LiDAR
      scan_line: 32
      timestamp_unit: 2
      blind: 0.5

    mapping:
      imu_en: True
      extrinsic_est_en: False
      imu_time_inte: 0.005
      lidar_time_inte: 0.1
      satu_acc: 30.0
      satu_gyro: 35.0
      acc_norm: 9.81
